fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
      name: "[file -  check] large file"
      args: [--maxkb=5000]
    - id: check-ast
      name: "[py   -  check] validate python"
    - id: check-builtin-literals
      name: "[py   -  check] builtin literals"
    - id: check-byte-order-marker
      name: "[file -  check] byte order marker"
    - id: check-case-conflict
      name: "[file -  check] case conflict"
    - id: check-docstring-first
      name: "[py   -  check] docstring first"
#    - id: check-executables-have-shebangs
#      name: "[sh   -  check] executable shebang"
    - id: check-json
      name: "[json -  check] validate json"
    - id: check-merge-conflict
      name: "[git  -  check] merge conflict"
    - id: check-symlinks
      name: "[link -  check] broken symlinks"
    - id: check-vcs-permalinks
      name: "[link -  check] vcs permalinks"
    - id: check-xml
      name: "[xml  -  check] validate xml"
    - id: check-yaml
      name: "[yaml -  check] validate yaml"
    - id: debug-statements
      name: "[py   -  check] debug statements"
    - id: detect-aws-credentials
      name: "[cred -  check] aws credentials"
      args: [--allow-missing-credentials]
    - id: detect-private-key
      name: "[cred -  check] private keys"
    - id: end-of-file-fixer
      name: "[py   - format] end of files"
    - id: fix-encoding-pragma
      name: "[file - format] coding pragma"
      args: [--remove]
    - id: forbid-new-submodules
      name: "[git  -  check] new submodules"
    - id: mixed-line-ending
      name: "[file - format] mixed line ending"
      args: [--fix=auto]
    - id: name-tests-test
      name: "[py   -  check] name tests test"
      args: [--django]
    - id: pretty-format-json
      name: "[json - format] pretty json"
      args: [--autofix, --indent=4, --no-sort-keys]
    - id: requirements-txt-fixer
      name: "[reqs - format] fix requirements.txt"
    - id: trailing-whitespace
      name: "[file - format] trim trailing whitespace"
      args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
        - id: isort
          # More info on black compatibility here:
          # "https://pycqa.github.io/isort/docs/configuration/black_compatibility.html"
          args: [--profile=black]
          name: "[py   - format] isort"

  - repo: https://github.com/PyCQA/docformatter
    # Currently, the formatter does not wrap descriptions when there are
    # "Parameters"/"Returns" sections in the docstring. There is currently an open
    # issue for that: "https://github.com/PyCQA/docformatter/issues/60#ref-issue-1418214386"
    # There is also an open issue to make `docformatter` compatible with black:
    # "https://github.com/PyCQA/docformatter/issues/94"
    rev: v1.6.0
    hooks:
      - id: docformatter
        args: [--wrap-summaries=88, --wrap-descriptions=88, -i]
        name: "[py   - format] docformatter"

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: [--convention=pep257]
        name: "[py   - check] pydocstyle"
        files: ^src/

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.0
    hooks:
      - id: flake8
        name: "[py   - check] flake8"
        language_version: python3.9

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        name: "[py   - format] black"
        language_version: python3.9

  # Bash auto-formatters and linters
  # --------------------------------

  # beautysh: A Bash beautifier.
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        name: "[bash - format] beautysh"

  # pre-commit-shell: Checks shell scripts against shellcheck.
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
        args: [--exclude=SC2034,SC2154,SC2059,SC2086,SC2086,SC2153,SC2148,SC2155,SC2002]
        name: "[bash -   lint] shell-lint"
