known_vendors = {
    "amzn": "amazon",
    "amazon": "amazon",
    "goodwill": "thrifting",
    "parking": "parking",
    "yellow jacket social": "drinking",
    "austin cidercade": "drinking",
    "brewing co": "drinking",
    "lustre pearl": "drinking",
    "jaeger &amp; lustig": "drinking",
    "bar": "drinking",
    "trudys south star": "drinking",
    "decathlon": "fitness",
    "mint mobile": "data plan",
    "turo": "rental",
    "cathaypacair": "air travel",
    "delta air": "air travel",
    "southwest": "air travel",
    "southwes": "air travel",
    "swa inflight wifi": "air travel",
    "airport": "air travel",
    "spirit airl": "air travel",
    "british a": "air travel",
    "ryanair": "air travel",
    "inflight purch": "air travel",
    "gotogate": "air travel",
    "gogoair": "air travel",
    "flynorse": "air travel",
    "hellweg": "hardware store",
    "bauhaus": "hardware store",
    "toom bm": "hardware store",
    "audible gmbh": "subscription",
    "laxshuttletix": "transport",
    "lyft": "transport",
    "uber": "transport",
    "pluckers": "fast food",
    "doubledave's": "fast food",
    "whataburger": "fast food",
    "tiki tatsu-ya": "fast food",
    "white castle": "fast food",
    "aust hut's burgers": "fast food",
    "taco cabana": "fast food",
    "church s chicken": "fast food",
    "india gourmet": "fast food",
    "bamboo bistro": "fast food",
    "pizza": "fast food",
    "trudys south star": "drinking",
    "apple store": "apple",
    "apple.com": "apple",
    "shell oil": "fuel",
    "nytimes": "news",
    "google *": "apps",
    "google*": "apps",
    "amazon.de": "amazon",
    "amazon prime": "amazon",
    "jcpenney": "shopping",
    "amz*": "amazon",
    "target": "shopping",
    "wisecars": "transport",
    "city of santa monica": "transport",
    "la transit reg norwalk": "transport",
    "goeuro corp": "transport",
    "international car": "transport",
    "payment": "payment",
    "dice.fm": "concerts",
    "greyzone concerts": "concerts",
    "gem  jam fes": "concerts",
    "tame impala": "concerts",
    "tommy want wingy": "fast food",
    "casa garcias": "fast food",
    "taqueria": "fast food",
    "deli": "fast food",
    "pinky's": "fast food",
    "au.renogy.com": "van costs",
    "rosetta stone": "learning",
    "coffee": "coffee",
    "cafe": "coffee",
    "royal blue": "snacks",
    "mechanical keyboards": "gear",
    "expressvpn": "gear",
    "samsung electronics": "gear",
    "doyourdata": "gear",
    "ereplacementparts": "gear",
    "twohappy": "gear",
    "goodrx gold": "shopping",
    "ebay": "shopping",
    "grand hotel cabin": "hotel",
    "spotify usa": "music",
    "rewe markt": "groceries",
    "sushi": "fast food",
    "tst* earl enterprises": "fast food",
    "timber and torch": "fast food",
    "omac shop gmbh": "van costs",
    "wienerschnitzel": "fast food",
    "purchase interest charge": "fees",
    "annual membership fee": "fees",
    "late fee": "fees",
    "thunderhead steamboat": "fast food",
    "pappadeaux": "fast food",
    "scryptcube": "cloud mining",
    "fnac faro": "shopping",
    "colibri gastro": "fast food",
    "tbjde gmbh": "fast food",
    "dell sales": "learning",
    "nickel city": "drinking",
    "paypal": "shopping",
    "wikimedia": "donation",
    "sesame care - health": "shopping",
}
